version: 2.1

executors:
  python-37:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
  python-38:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/repo
  python-39:
    docker:
      - image: circleci/python:3.9
    working_directory: ~/repo

commands:
  build:
    description: "Download and build"
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: poetry install --no-dev
  test:
    description: "Download and run tests"
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: poetry install --no-dev
      - run:
          name: Run unit tests
          command: poetry run python manage.py test selene --settings selene.tests.settings
  test-with-codecov:
    description: "Download and run tests with code coverage"
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: poetry install
      - run:
          name: Install codecov
          command: poetry run pip install codecov
      - run:
          name: Run unit tests
          command: poetry run coverage run --source=selene manage.py test selene --settings selene.tests.settings
      - run:
          name: Upload coverage to Codecov
          command: poetry run codecov
  lint:
    description: "Lint python files"
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: poetry install
      - run:
          name: Check with black
          command: poetry run black --check .
      - run:
          name: Check with pylint
          command: poetry run pylint  --disable=R --django-settings-module=hyperion.settings selene hyperion
      - run:
          name: Check version information
          command: poetry run python -m pontos.version verify current

jobs:
  build-37:
    executor: python-37
    steps:
      - build
  test-37:
    executor: python-37
    steps:
      - test-with-codecov
  build-38:
    executor: python-38
    steps:
      - build
  test-38:
    executor: python-38
    steps:
      - test
  build-39:
    executor: python-39
    steps:
      - build
  test-39:
    executor: python-39
    steps:
      - test
  lint-37:
    executor: python-37
    steps:
      - lint

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-37
      - test-37
      - lint-37
      - build-38
      - test-38
      - build-39
      - test-39
